training_config:
  wandb_project: "uniworld-1024-s1-explicit-short-v2.0.0"
  wandb_name: "stage1_from_univa_v2-ckpt-4000_1024_adamW_1e-5"
  seed: 203
  output_dir: ./checkpoints/"stage1_from_univa_v2-ckpt-4000_1024_adamW_1e-5"
  logging_dir: ./logs/"stage1_from_univa_v2-ckpt-4000_1024_adamW_1e-5"
  max_train_steps: 500000
  optimizer: "adamw"
  learning_rate: 1e-5
  adam_beta1: 0.9
  adam_beta2: 0.99
  adam_epsilon: 1e-8
  adam_weight_decay: 0.0
  mixed_precision: "bf16"
  report_to: "wandb"
  gradient_checkpointing: true
  num_train_epochs: 1
  lr_scheduler: "constant"
  lr_warmup_steps: 0
  lr_num_cycles: 1
  lr_power: 1.0
  resume_from_checkpoint: null
  validation_steps: 200
  checkpointing_steps: 1000
  drop_t5_rate: 1.0
  discrete_timestep: false
  mask_weight_type: 'log'
  gradient_accumulation_steps: 1
  ema_deepspeed_config_file: null #scripts/accelerate_configs/zero1.json
  ema_decay: 0.999

model_config:
  pretrained_lvlm_name_or_path: /workspace/UniWorld-V1/model_weight/uniworld-stage-2-1024-v2.0.0_ckpt-4000
  ema_pretrained_lvlm_name_or_path: null #/workspace/UniWorld-V1/model_weight/UniWorld-V1
  pretrained_denoiser_name_or_path: /workspace/UniWorld-V1/model_weight/FLUX.1-dev
  guidance_scale: 1.0
  only_tune_mlp2: true
  with_tune_mlp2: false
  pretrained_mlp2_path: /workspace/UniWorld-V1/checkpoints/flux_qwen2p5vl_7b_vlm_stage1_from_univa_v1_1024_adamW_1e-5/checkpoint-1000/denoise_projector.bin
  only_tune_mlp3: false
  with_tune_mlp3: false
  pretrained_mlp3_path: null  
  only_tune_siglip_mlp: false
  with_tune_siglip_mlp: false
  pretrained_siglip_mlp_path: /workspace/UniWorld-V1/model_weight/uniworld-stage-2-1024-v2.0.0_ckpt-4000/siglip_projector.bin
  joint_ref_feature: false
  only_use_t5: false
  only_tune_image_branch: false

dataset_config:
  padding_side: "left"
  ocr_enhancer: false
  dataset_type: qwen2p5vl
  min_pixels: 1048576
  max_pixels: 1048576
  data_txt: /workspace/UniWorld-V1/training_data/uniworld_removal_dataset_v2.0.0/data.txt
  batch_size: 4
  num_workers: 16
  height: 1024
  width: 1024
  pin_memory: true

  validation_cases:
    # Empty
    - validation_it2i_prompt: "Remove bed, clothes, bags, suitcase, portable air conditioner, fan, appliance, shoe racks, shoes, box, ironing board, clothes rack, poster, small table. <image>"
      validation_image_path: assets/removal_2.jpg

    - validation_it2i_prompt: "Remove table, office chair, woven chair, laptop, printer, stool, shelving unit, lamp, vase, clothing racks, clothes, hangers, orange chair, dressing mannequin, shoes, coffee table, blue chair, papers, boxes. <image>"
      validation_image_path: assets/removal_5.jpg

    - validation_it2i_prompt: "Empty room. <image>"
      validation_image_path: assets/removal_2.jpg

    - validation_it2i_prompt: "Empty room. <image>"
      validation_image_path: assets/removal_5.jpg

    # Clean
    - validation_it2i_prompt: "Remove red dumbbells, yellow jump rope, cardboard boxes, laptop, small potted plant, globe, red jars, electronics and cables on the TV console, pink fabric, white pet bed. <image>"
      validation_image_path: assets/removal_1.jpg

    - validation_it2i_prompt: "Remove a black bag, small items on the nightstand, a rolled-up rug, folded clothes, and a white heater unit. <image>"
      validation_image_path: assets/removal_3.jpg
      
    - validation_it2i_prompt: "Clean room. <image>"
      validation_image_path: assets/removal_1.jpg

    - validation_it2i_prompt: "Clean room. <image>"
      validation_image_path: assets/removal_3.jpg